### ISSUE TITLE
Generación de posiciones al mover el modelo 3D

### ISSUE THREAD

**Issue by KeilerX** [KeilerX/CC55_BRAZOROBOTICO#7]

**Comment by jonathandeoz** [comment]
Agregados controles que generan movimiento del brazo por articulacion, la posicion puede ser calculada en cualquier momento.

**Comment by jonathandeoz** [comment]
Agregados controles que generan movimiento del brazo por articulacion, la posicion puede ser calculada en cualquier momento.
